### ISSUE TITLE
Muver error: run_pipeline

### ISSUE THREAD

**Issue by hollygene** [NIEHS/muver#4]
* MuVer version: 0.1.0
* Python version: 2.7.14
* Operating System: UGA Sapelo2 Cluster (https://wiki.gacrc.uga.edu/wiki/Georgia_Advanced_Computing_Resource_Center)

### Description
Hi, 

I am attempting to run Muver on a few samples. I had my institution (University of Georgia) install Muver on their cluster computing system. Below I pasted my commands and what the output was. I have asked UGA's cluster staff for insights, but they suggested contacting you guys as they don't know what the problem is either. 

Any help will be greatly appreciated! 
Thank you!
-Holly

### What I Did

```
#PBS -S /bin/bash
#PBS -N muver
#PBS -q batch
#PBS -l nodes=1:ppn=1:AMD
#PBS -l mem=50gb
#PBS -l walltime=480:00:00


cd $PBS_O_WORKDIR
module load muver/0.1.0-foss-2016b-Python-2.7.14
mkdir "/scratch/hcm14449/TE_MA_Paradoxus/Practice/output.2"
data_dir="/scratch/hcm14449/TE_MA_Paradoxus/Practice/files/samples"
ref_genome="/scratch/hcm14449/TE_MA_Paradoxus/Practice/files/ref_genome/SCerevisiae.RefGenome.fa"
fastq_list="/home/hcm14449/Github/TE_MA/fastq_list_2.txt"
control_sample_name="Ancestor"
experiment_directory="/scratch/hcm14449/TE_MA_Paradoxus/Practice/output.2"



#index reference genome

muver index-reference ${ref_genome}
#
# create repeat file for reference genome
muver create-repeat-file ${ref_genome}

# run the pipeline
muver run-pipeline ${ref_genome} ${fastq_list} ${control_sample_name} ${experiment_directory}

### traceback of crash
To execute GATK run: java -jar $EBROOTGATK/GenomeAnalysisTK.jar
    To execute picard run: java -jar $EBROOTPICARD/picard.jar
/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/site-packages/scipy-0.19.1-py2.7-linux-x86_64.egg/scipy/stats/_continuous_distns.py:184: RuntimeWarning: Mean of empty slice.
  loc = data.mean()
/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/site-packages/scipy-0.19.1-py2.7-linux-x86_64.egg/scipy/stats/_continuous_distns.py:189: RuntimeWarning: Mean of empty slice.
  scale = np.sqrt(((data - loc)**2).mean())
/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/site-packages/numpy/lib/function_base.py:817: RuntimeWarning: invalid value encountered in true_divide
  return n/db/n.sum(), bins
Traceback (most recent call last):
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/bin/muver", line 11, in <module>
    load_entry_point('muver==0.1.0', 'console_scripts', 'muver')()
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/muver-0.1.0-py2.7.egg/muver/cli.py", line 71, in run_pipeline
    max_records=max_records,
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/muver-0.1.0-py2.7.egg/muver/pipeline.py", line 226, in run_pipeline
    [s.cnv_regions for s in samples],
  File "/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
ValueError: array must not contain infs or NaNs

```

**Comment by burkholderab** [comment]
Hi Holly,

It looks like the error is occurring as muver attempts to determine parameters for the strand bias and depth distributions.  To help us narrow down the problem, could you provide a list of the files within your output directory, including their sizes and timestamps (i.e. the output of ls -lR /scratch/hcm14449/TE_MA_Paradoxus/Practice/output.2)?

Thanks,

Adam

**Comment by hollygene** [comment]
Hi Adam,
Sure, here's the output: 
```
hcm14449@sapelo2-sub1 output.2$ ls -lR
.:
total 192
drwxr-xr-x. 2 hcm14449 dwhlab  4096 Feb 12 20:42 bams
drwxr-xr-x. 2 hcm14449 dwhlab  4096 Feb 12 16:09 depth_distributions
drwxr-xr-x. 2 hcm14449 dwhlab  4096 Feb 12 16:09 filtered_sites
drwxr-xr-x. 2 hcm14449 dwhlab  4096 Feb 12 16:09 fits
drwxr-xr-x. 2 hcm14449 dwhlab  4096 Feb 12 16:09 gatk_output
drwxr-xr-x. 2 hcm14449 dwhlab  4096 Feb 12 16:09 logs
drwxr-xr-x. 2 hcm14449 dwhlab  4096 Feb 12 16:09 output
-rw-r--r--. 1 hcm14449 dwhlab 36880 Feb 12 20:42 tmp37Z40W.bam.bai
-rw-r--r--. 1 hcm14449 dwhlab 36744 Feb 12 20:00 tmpE_gPo3.bam.bai
-rw-r--r--. 1 hcm14449 dwhlab 36720 Feb 12 20:17 tmpJkVrmc.bam.bai
-rw-r--r--. 1 hcm14449 dwhlab 36432 Feb 12 19:44 tmpjoneUM.bam.bai
drwxrw-rw-. 2 hcm14449 dwhlab  4096 Feb 12 20:11 tmpk3X34z
drwxrw-rw-. 2 hcm14449 dwhlab  4096 Feb 12 19:42 tmpobFc9_
drwxrw-rw-. 2 hcm14449 dwhlab  4096 Feb 12 20:33 tmpT4l3cV
drwxrw-rw-. 2 hcm14449 dwhlab  4096 Feb 12 19:55 tmpT_H8MU

./bams:
total 32
-rw-r--r--. 1 hcm14449 dwhlab 92 Feb 12 19:44 Ancestor.bam
-rw-r--r--. 1 hcm14449 dwhlab 16 Feb 12 19:44 Ancestor.bam.bai
-rw-r--r--. 1 hcm14449 dwhlab 92 Feb 12 20:00 Sample29.bam
-rw-r--r--. 1 hcm14449 dwhlab 16 Feb 12 20:00 Sample29.bam.bai
-rw-r--r--. 1 hcm14449 dwhlab 92 Feb 12 20:17 Sample2.bam
-rw-r--r--. 1 hcm14449 dwhlab 16 Feb 12 20:17 Sample2.bam.bai
-rw-r--r--. 1 hcm14449 dwhlab 92 Feb 12 20:42 Sample32.bam
-rw-r--r--. 1 hcm14449 dwhlab 16 Feb 12 20:42 Sample32.bam.bai

./depth_distributions:
total 0

./filtered_sites:
total 0

./fits:
total 0

./gatk_output:
total 0

./logs:
total 0

./output:
total 0

./tmpk3X34z:
total 0

./tmpobFc9_:
total 0

./tmpT4l3cV:
total 0

./tmpT_H8MU:
total 0
```
Thanks!
-Holly

**Comment by burkholderab** [comment]
Thanks, Holly.  I was able to recreate the issue you're seeing by restoring the "paths.cfg" file to its default state.  Can you ensure that the paths to the picard tools and GATK3 jar files, as well as the bowtie2 and samtools executables are accurate for your system?  You should find the file here:  /usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/muver-0.1.0-py2.7.egg/config.

**Comment by hollygene** [comment]
Thanks Adam! 
I re-ran the pipeline and it ran for much longer this time (about 36 hours I think, with 200GB of memory and 2 threads). However there was still an issue. Here is the error reported:

```
To execute GATK run: java -jar $EBROOTGATK/GenomeAnalysisTK.jar
    To execute picard run: java -jar $EBROOTPICARD/picard.jar
Traceback (most recent call last):
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/bin/muver", line 11, in <module>
    load_entry_point('muver==0.1.0', 'console_scripts', 'muver')()
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/muver-0.1.0-py2.7.egg/muver/cli.py", line 71, in run_pipeline
    max_records=max_records,
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14/lib/python2.7/site-packages/muver-0.1.0-py2.7.egg/muver/pipeline.py", line 241, in run_pipeline
    [s.repeat_indel_header for s in samples],
  File "/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
IndexError: list index out of range
```

And here is the output from the output.3 folder:
```
hcm14449@sapelo2-sub1 output.3$ ls -lR
.:
total 360
drwxr-xr-x. 2 hcm14449 dwhlab  4096 Feb 18 20:54 bams
drwxr-xr-x. 2 hcm14449 dwhlab  4096 Feb 19 22:05 depth_distributions
drwxr-xr-x. 2 hcm14449 dwhlab  4096 Feb 19 22:11 filtered_sites
drwxr-xr-x. 2 hcm14449 dwhlab  4096 Feb 19 22:23 fits
drwxr-xr-x. 2 hcm14449 dwhlab  4096 Feb 19 20:27 gatk_output
drwxr-xr-x. 2 hcm14449 dwhlab  4096 Feb 18 20:54 logs
drwxr-xr-x. 2 hcm14449 dwhlab  4096 Feb 18 15:39 output
drwxrw-rw-. 2 hcm14449 dwhlab  4096 Feb 18 20:48 tmp4LPChT
-rw-r--r--. 1 hcm14449 dwhlab 36880 Feb 18 20:04 tmpaKcqu6.bam.bai
drwxrw-rw-. 2 hcm14449 dwhlab  4096 Feb 18 19:02 tmpDQw_pk
drwxrw-rw-. 2 hcm14449 dwhlab  4096 Feb 18 18:32 tmpgDqHWZ
-rw-r--r--. 1 hcm14449 dwhlab 36720 Feb 18 19:16 tmpl3iD_N.bam.bai
-rw-r--r--. 1 hcm14449 dwhlab 37088 Feb 18 20:41 tmpLOpN3g.bai
-rw-r--r--. 1 hcm14449 dwhlab 36432 Feb 18 18:23 tmpoOXnpO.bam.bai
-rw-r--r--. 1 hcm14449 dwhlab 36744 Feb 18 18:43 tmpQFAuqR.bam.bai
-rw-r--r--. 1 hcm14449 dwhlab 37016 Feb 18 19:40 tmptp1Rwe.bai
-rw-r--r--. 1 hcm14449 dwhlab 37008 Feb 18 18:58 tmpY1IyKk.bai
-rw-r--r--. 1 hcm14449 dwhlab 36768 Feb 18 18:30 tmpYGSz9T.bai
drwxrw-rw-. 2 hcm14449 dwhlab  4096 Feb 18 19:45 tmpYY9uZs

./bams:
total 2456600
-rw-r--r--. 1 hcm14449 dwhlab  206334724 Feb 18 18:33 Ancestor.bam
-rw-r--r--. 1 hcm14449 dwhlab      36496 Feb 18 18:33 Ancestor.bam.bai
-rw-r--r--. 1 hcm14449 dwhlab  632778138 Feb 18 19:05 Sample29.bam
-rw-r--r--. 1 hcm14449 dwhlab      36752 Feb 18 19:06 Sample29.bam.bai
-rw-r--r--. 1 hcm14449 dwhlab  673092657 Feb 18 19:49 Sample2.bam
-rw-r--r--. 1 hcm14449 dwhlab      36752 Feb 18 19:49 Sample2.bam.bai
-rw-r--r--. 1 hcm14449 dwhlab 1003176338 Feb 18 20:54 Sample32.bam
-rw-r--r--. 1 hcm14449 dwhlab      36912 Feb 18 20:54 Sample32.bam.bai

./depth_distributions:
total 1041660
-rw-r--r--. 1 hcm14449 dwhlab 191010885 Feb 19 20:34 Ancestor.bedGraph
-rw-r--r--. 1 hcm14449 dwhlab     43359 Feb 19 20:35 Ancestor.depth_distribution.txt
-rw-r--r--. 1 hcm14449 dwhlab      3953 Feb 19 20:32 Ancestor.strand_bias_distribution.txt
-rw-r--r--. 1 hcm14449 dwhlab 285835205 Feb 19 20:56 Sample29.bedGraph
-rw-r--r--. 1 hcm14449 dwhlab     89522 Feb 19 21:00 Sample29.depth_distribution.txt
-rw-r--r--. 1 hcm14449 dwhlab      4010 Feb 19 20:52 Sample29.strand_bias_distribution.txt
-rw-r--r--. 1 hcm14449 dwhlab 284371074 Feb 19 21:24 Sample2.bedGraph
-rw-r--r--. 1 hcm14449 dwhlab    101376 Feb 19 21:28 Sample2.depth_distribution.txt
-rw-r--r--. 1 hcm14449 dwhlab      4001 Feb 19 21:19 Sample2.strand_bias_distribution.txt
-rw-r--r--. 1 hcm14449 dwhlab 304993340 Feb 19 22:00 Sample32.bedGraph
-rw-r--r--. 1 hcm14449 dwhlab    169001 Feb 19 22:05 Sample32.depth_distribution.txt
-rw-r--r--. 1 hcm14449 dwhlab      4002 Feb 19 21:53 Sample32.strand_bias_distribution.txt

./filtered_sites:
total 40
-rw-r--r--. 1 hcm14449 dwhlab  2225 Feb 19 20:40 Ancestor.filtered_sites.bed
-rw-r--r--. 1 hcm14449 dwhlab 10616 Feb 19 21:07 Sample29.filtered_sites.bed
-rw-r--r--. 1 hcm14449 dwhlab  9387 Feb 19 21:35 Sample2.filtered_sites.bed
-rw-r--r--. 1 hcm14449 dwhlab 10553 Feb 19 22:14 Sample32.filtered_sites.bed

./fits:
total 8
-rw-r--r--. 1 hcm14449 dwhlab 12 Feb 19 22:23 Ancestor.repeat_indel_fits.rates.txt
-rw-r--r--. 1 hcm14449 dwhlab 30 Feb 19 22:23 Ancestor.repeat_indel_fits.txt

./gatk_output:
total 36732
-rw-r--r--. 1 hcm14449 dwhlab 37557813 Feb 19 20:27 haplotype_caller_output.vcf
-rw-r--r--. 1 hcm14449 dwhlab    47028 Feb 19 20:27 haplotype_caller_output.vcf.idx

./logs:
total 260
-rw-r--r--. 1 hcm14449 dwhlab   4685 Feb 18 18:30 Ancestor.realignment.0.log
-rw-r--r--. 1 hcm14449 dwhlab 217546 Feb 19 20:27 haplotype_caller.log
-rw-r--r--. 1 hcm14449 dwhlab   6066 Feb 18 18:58 Sample29.realignment.0.log
-rw-r--r--. 1 hcm14449 dwhlab   8463 Feb 18 19:40 Sample2.realignment.0.log
-rw-r--r--. 1 hcm14449 dwhlab  11432 Feb 18 20:41 Sample32.realignment.0.log

./output:
total 0

./tmp4LPChT:
total 0

./tmpDQw_pk:
total 0

./tmpgDqHWZ:
total 0

./tmpYY9uZs:
total 0
```

It definitely did a lot more this time, but I'm not sure where it got hung up this time. Any help is greatly appreciated! 
Thank you!!

**Comment by burkholderab** [comment]
Hi Holly,

It looks like the failure is occurring when muver is attempting to plot the relationship between indel error rates and repeat unit/tract length.  Can you check to make sure the python package "matplotlib" is installed and capable of writing png files?  At one point I ran into a matplotlib issue that I resolved by specifying the use of the "Agg" backend to render the images.  This is implemented in the "update" branch here:  https://github.com/NIEHS/muver/blob/update/muver/repeat_indels.py.

You can test this functionality without re-running the full pipeline with the command "muver fit_repeat_indel_rates".

Thanks,

Adam

**Comment by hollygene** [comment]
Hi Adam, 
I got help from our cluster's staff, and this was their response:

"I tested your job and reproduced the error that you got. I checked that the matplotlib installed with Python 2.7.14 that muver uses can save png files. And as a further test, I added the Agg backend to repeat_indels.py, as described at https://github.com/NIEHS/muver/blob/update/muver/repeat_indels.py and tried your job again. The same error is still occurring (the repeat_indels.py file in place now is the one from the link above).

It looks like the error occurs in the code in repeat_indels.py:
```
for repeat_length in (1, 2, 3, 4):
for event in ('insertion', 'deletion'):
f.write('\t' + event + '_' + str(repeat_length))
curmax = sorted(indel_rates[event][repeat_length].keys(), \
reverse=True)[0]
if curmax > max:
max = curmax
```
The code fails when it runs the sorted() function for repeat_length=1 and event=insertion. It looks like the code is trying to access an element that is not defined in a list.

What are these input files that you are using? Are these sample data? My only thought now is that there is something not defined correctly in the input files (or their size is too large and some pre-set limit in the muver code is not suitable to handle this data set). " 

The files I input from the beginning were .fastq files and should be okay. I can double-check the quality of them to be sure, though. 

Any insights would be super helpful!! 

Thank you!
-Holly

**Comment by burkholderab** [comment]
Hi Holly,

Thanks for the detailed information.  There shouldn't be any type of internal limit on read count or depth within muver that could be causing this issue, and your BAM files are actually smaller than those I typically analyze.  Based where the error is occurring, and the fact that the indel error rate fit file is nearly empty (Ancestor.repeat_indel_fits.txt), there appears to be a problem with observing apparent indels within the reads, and localizing those to the pre-defined repeat tracts.  Can you ensure that your repeat file "/scratch/hcm14449/TE_MA_Paradoxus/Practice/files/ref_genome/SCerevisiae.RefGenome.repeats" exists and is not empty.  My repeat file for S. cerevisiae assembly S288C is around 88 Mb, and I would expect yours to be a comparable size.

It also occurs to me that there might be a discrepancy between the chromosome names in the repeat file and those in the BAM file if the FASTA headers contain spaces.  I've modified "repeats.py" to try to resolve that potential issue.  I've also modifed "repeat_indels.py" to prevent the specific error you're seeing, though, I can't guarantee other issues won't crop up if the underlying problem isn't corrected.  You can find the new code in the "update" branch.  Please update your local copy, generate a new repeat file, and let me know if you're able to run "muver fit_repeat_indel_rates" without errors.

Thanks,

Adam

**Comment by hollygene** [comment]
Hi Adam, 

Thank you for this help! My repeats file is 110 Mb. I ran muver fit_repeat_indel_rates and it worked fine! 

I ran the full pipeline again, however, and received a NEW error (if it's not one thing it's the other, right?) 

``` 
To execute GATK run: java -jar $EBROOTGATK/GenomeAnalysisTK.jar
    To execute picard run: java -jar $EBROOTPICARD/picard.jar
Traceback (most recent call last):
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14-20190318/bin/muver", line 11, in <module>
    load_entry_point('muver==0.1.0', 'console_scripts', 'muver')()
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14-20190318/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14-20190318/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14-20190318/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14-20190318/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14-20190318/lib/python2.7/site-packages/Click-7.0-py2.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14-20190318/lib/python2.7/site-packages/muver-0.1.0-py2.7.egg/muver/cli.py", line 71, in run_pipeline
    max_records=max_records,
  File "/usr/local/apps/eb/muver/0.1.0-foss-2016b-Python-2.7.14-20190318/lib/python2.7/site-packages/muver-0.1.0-py2.7.egg/muver/pipeline.py", line 241, in run_pipeline
    [s.repeat_indel_header for s in samples],
  File "/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
_tkinter.TclError: no display name and no $DISPLAY environment variable
``` 
I'm not sure where to go from here, so any insights would be awesome! 

Thank you so much!
-Holly

**Comment by burkholderab** [comment]
Hi Holly,

The error you're seeing now is the one I mentioned earlier, related to the matplotlib backend.  I removed the fix for this in the most recent update because I was concerned overriding the system default would be more likely to cause problems than solve them.  You can find a copy of "repeat_indels.py" with this fix applied here:  https://github.com/NIEHS/muver/blob/6d3d03292238be70749470f214e654f7dcb26a98/muver/repeat_indels.py.  Try replacing your current version with this and reinstalling.

Thanks,

Adam

**Comment by hollygene** [comment]
Hi Adam, 

It looks like that did the trick! I'm pretty sure I got all of the output files expected. Thank you so much for all of the help, and I will let you know if I run into any more troubles. 

Best,
Holly
