### ISSUE TITLE
run muver on FASTA instead of FASTQ

### ISSUE THREAD

**Issue by MariusGheorghe** [NIEHS/muver#6]
Hi,

Was wondering if it is possible to run muver starting from FASTA files instead of FASTQ file. 
I see that the `run_pipeline` requires the `FASTQ_list` with mate 1 and 2 columns, information that I do not have. 

Please let me know. Thank you in advance!

Marius

**Comment by burkholderab** [comment]
Hi Marius,

Muver was designed to work with Illumina sequencing data, which is typically delivered in FASTQ format. If you have next generation sequencing reads in FASTA format, the pipeline can be run manually, however, the process is lengthy, and requires some commands be run with specific parameters to maintain compatibility with downstream steps. If you are able to install the package from github rather than utilizing the docker container, a minor modification of this file, https://github.com/NIEHS/muver/raw/master/muver/wrappers/bowtie2.py, can add support for FASTA input. Simply change the parameter on line 34 from '-q' to '-f', which indicates that the aligner, bowtie2, should expect FASTA rather than FASTQ input. When you generate the “FASTQ_list” file, you can include just the “Mate 1 FASTQ” column, just as you would with single-end FASTQ input, but list the names of your FASTA files instead.

You may be able to replace the original with an updated copy within the docker container by specifying ‘-u 0’ in the run command to enter the shell as root. The file to be replaced is:

/usr/local/lib/python2.7/dist-packages/muver-0.1.0-py2.7.egg/muver/wrappers/bowtie2.py

…and you can place the modified copy in your mounted data directory.

I was able perform the modification successfully on two different Linux-based docker environments, however, depending on how your system is configured, this approach may not work for you.

Thanks,

Adam

**Comment by MariusGheorghe** [comment]
Hi Adam,

Thank you for you quick and detailed reply.

I knew that there is an option in `bowtie` for it but after trying to fiddle with the docker image and get access to the source code from within it and having it failed several times (including the standalone installation due to errors in the dependencies installation [#7 ](https://github.com/NIEHS/muver/issues/7) I gave up.

For now, I have converted FASTA to FASTQ with some fake scores, but will follow your instructions and modify the code hopefully and launch the pipeline. 

I read more carefully the doc and I eventually figured out that FASTQ mate 2 is not actually mandatory.

Thanks again for the support!

Marius

**Comment by MariusGheorghe** [comment]
Hi again,

When trying to install it from the GIT repo, under python 2.7 I get an error. Complete log below:
```
marius@onco:~/projects/genomes/muver$ sudo python2.7 setup.py install
running install
running bdist_egg
running egg_info
writing requirements to muver.egg-info/requires.txt
writing muver.egg-info/PKG-INFO
writing top-level names to muver.egg-info/top_level.txt
writing dependency_links to muver.egg-info/dependency_links.txt
writing entry points to muver.egg-info/entry_points.txt
reading manifest file 'muver.egg-info/SOURCES.txt'
writing manifest file 'muver.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/reference.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/__init__.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/fitting.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/read_processing.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/allelic_fraction.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/utils.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/pipeline.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/repeats.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/cli.py -> build/bdist.linux-x86_64/egg/muver
creating build/bdist.linux-x86_64/egg/muver/wrappers
copying build/lib.linux-x86_64-2.7/muver/wrappers/__init__.py -> build/bdist.linux-x86_64/egg/muver/wrappers
copying build/lib.linux-x86_64-2.7/muver/wrappers/bowtie2.py -> build/bdist.linux-x86_64/egg/muver/wrappers
copying build/lib.linux-x86_64-2.7/muver/wrappers/samtools.py -> build/bdist.linux-x86_64/egg/muver/wrappers
copying build/lib.linux-x86_64-2.7/muver/wrappers/picard.py -> build/bdist.linux-x86_64/egg/muver/wrappers
copying build/lib.linux-x86_64-2.7/muver/wrappers/gatk.py -> build/bdist.linux-x86_64/egg/muver/wrappers
copying build/lib.linux-x86_64-2.7/muver/variant_list.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/depth_ratios.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/repeat_indels.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/depth_distribution.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/bias_distribution.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/variant.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/sample.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/depth_correction.py -> build/bdist.linux-x86_64/egg/muver
copying build/lib.linux-x86_64-2.7/muver/call_mutations.py -> build/bdist.linux-x86_64/egg/muver
byte-compiling build/bdist.linux-x86_64/egg/muver/reference.py to reference.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/fitting.py to fitting.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/read_processing.py to read_processing.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/allelic_fraction.py to allelic_fraction.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/pipeline.py to pipeline.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/repeats.py to repeats.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/cli.py to cli.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/wrappers/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/wrappers/bowtie2.py to bowtie2.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/wrappers/samtools.py to samtools.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/wrappers/picard.py to picard.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/wrappers/gatk.py to gatk.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/variant_list.py to variant_list.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/depth_ratios.py to depth_ratios.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/repeat_indels.py to repeat_indels.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/depth_distribution.py to depth_distribution.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/bias_distribution.py to bias_distribution.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/variant.py to variant.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/sample.py to sample.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/depth_correction.py to depth_correction.pyc
byte-compiling build/bdist.linux-x86_64/egg/muver/call_mutations.py to call_mutations.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/config
copying paths.cfg -> build/bdist.linux-x86_64/egg/config
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying muver.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying muver.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying muver.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying muver.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying muver.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying muver.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying muver.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/muver-0.1.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing muver-0.1.0-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/muver-0.1.0-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/muver-0.1.0-py2.7.egg
Extracting muver-0.1.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
muver 0.1.0 is already the active version in easy-install.pth
Installing muver script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/muver-0.1.0-py2.7.egg
Processing dependencies for muver==0.1.0
Searching for scipy>=0.18.1
Reading https://pypi.org/simple/scipy/
Downloading https://files.pythonhosted.org/packages/04/ab/e2eb3e3f90b9363040a3d885ccc5c79fe20c5b8a3caa8fe3bf47ff653260/scipy-1.4.1.tar.gz#sha256=dee1bbf3a6c8f73b6b218cb28eed8dd13347ea2f87d572ce19b289d6fd3fbc59
Best match: scipy 1.4.1
Processing scipy-1.4.1.tar.gz
Writing /tmp/easy_install-5z5aLu/scipy-1.4.1/setup.cfg
Running scipy-1.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5z5aLu/scipy-1.4.1/egg-dist-tmp-FPpPMM
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    data_files=[('config', ['paths.cfg'])],
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 660, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 707, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 752, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/marius/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/home/marius/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/marius/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/marius/.local/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-5z5aLu/scipy-1.4.1/setup.py", line 31, in <module>
    name='muver',
RuntimeError: Python version >= 3.5 required.
```
I can install it successfully under python 3.6, but when trying to run the `index_reference` I get the error:
```
marius@onco:~/projects/genomes/test_muver_fasta$ muver index_reference wuhan_hu1.fa 
Traceback (most recent call last):
  File "/usr/local/bin/muver", line 11, in <module>
    load_entry_point('muver==0.1.0', 'console_scripts', 'muver')()
  File "/home/marius/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/marius/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2853, in load_entry_point
    return ep.load()
  File "/home/marius/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2444, in load
    return self.resolve()
  File "/home/marius/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/muver-0.1.0-py3.6.egg/muver/cli.py", line 8, in <module>
    from allelic_fraction import get_allelic_fractions
ModuleNotFoundError: No module named 'allelic_fraction'
```

Will then try to replace the `bowtie2` wrapper inside the Docker image and try running it from there. 

Becomes messy for such simple tasks

Marius

**Comment by MariusGheorghe** [comment]
OK. I ran the docker image with the `-u 0` parameter setting, as you mentioned, to be root and replaced the `bowtie2` wrapper with the "custom" version for FASTA. 

Now it seems to work (i.e., no crash yet) :]
Hopefully it will complete successfully

Thank you for your support. Will bug you if I run in other problems :grin:
I consider the issue closed

Marius

**Comment by burkholderab** [comment]
It seems your problem is related to python 2.7 compatibility issues among some of the dependencies, particularly scipy. I’ve modified the install script to limit versions of dependencies to those released prior to the January 1st, 2020 deprecation deadline for python 2.7 and created a new release of muver, 1.2.1. I will investigate the python 3 compatibility issue in the near future.

Thanks,

Adam

**Comment by MariusGheorghe** [comment]
Hi Adam, 

Yeah, saw it was complaining about `scipy`, but just wanted to post the installation log here to help you and others running into the same problem.

Thanks for taking your time for the fix! 

The pipeline I launched a couple of hours ago is still running (I hope.. at least the processors are sweating) but dunno where the workflow is wrt to completion, as there is no textual output to provide feedback. Is that normal? Let's hope it finishes :crossed_fingers: 

Marius

**Comment by burkholderab** [comment]
There will generally be no text output to the console, however, the indel realignment and identification of potential mutations performed by GATK will write output to the “logs” folder under your results directory.

**Comment by MariusGheorghe** [comment]
Oki doki
Thanks! :+1:
